# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - 3.7
  - 3.6
  - 3.5
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3.sh;
  - bash miniconda3.sh -b -p $HOME/miniconda3
  - source $HOME/miniconda3/etc/profile.d/conda.sh
  - conda activate
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda create -q -n test_env python=$TRAVIS_PYTHON_VERSION
  - conda activate test_env
  - conda config --append channels conda-forge
  - conda install qutip>=4.0,!=4.4.0
  # we must use an editable install, otherwise coveralls won't work
  - PIP_USE_PEP517=false pip install -e .[dev]
  - pip install coveralls
  - pip freeze

script:
  - set -e
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then isort --recursive --check-only src tests; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then black --skip-string-normalization --line-length 79 --check src tests; fi
  - py.test --doctest-modules --cov=krotov --nbval --sanitize-with docs/nbval_sanitize.cfg --durations=10 src tests docs/notebooks/*.ipynb README.rst docs/*.rst
after_success:
  - coveralls
