# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
matrix:
  fast_finish: true
  include:
    - name: Check codestyle
      python: 3.7
      env: TOTEST="" TOXENV="run-blackcheck,run-isortcheck" TRAVISCMD=""
    - name: Docs
      python: 3.7
      env: TOTEST="" TOXENV=docs TRAVISCMD=""
      addons:
        apt_packages:
          - pandoc
          - pandoc-citeproc
    - name: Python 3.5
      python: 3.5
      env: TOTEST="src tests README.rst docs/*.rst" TOXENV=py35-test TRAVISCMD=""
    - name: Python 3.6
      python: 3.6
      env: TOTEST="src tests README.rst docs/*.rst" TOXENV=py36-test TRAVISCMD=""
    - name: Python 3.7
      python: 3.7
      env: TOTEST="src tests README.rst docs/*.rst" TOXENV=py37-test TRAVISCMD=""
    - name: Python 3.8-dev
      python: 3.8-dev
      env: TOTEST="src tests README.rst docs/*.rst" TOXENV=py38dev-test TRAVISCMD=""
    - name: Notebook 1 (State-to-State)
      python: 3.7
      env: TOTEST=docs/notebooks/01_example_simple_state_to_state.ipynb TOXENV=py37-test TRAVISCMD=""
    - name: Notebook 2 (RWA)
      python: 3.7
      env: TOTEST=docs/notebooks/02_example_lambda_system_rwa_complex_pulse.ipynb TOXENV=py37-test TRAVISCMD=""
    - name: Notebook 3 (Non-Hermitian)
      python: 3.7
      env: TOTEST=docs/notebooks/03_example_lambda_system_rwa_non_hermitian.ipynb TOXENV=py37-test TRAVISCMD=""
    - name: Notebook 4 (Density Matrix)
      python: 3.7
      env: TOTEST=docs/notebooks/04_example_dissipative_qubit_reset.ipynb TOXENV=py37-test TRAVISCMD=""
    - name: Notebook 5 (Quantum Gate)
      python: 3.7
      env: TOTEST=docs/notebooks/05_example_transmon_xgate.ipynb TOXENV=py37-test TRAVISCMD=""
    - name: Notebook 6 (3 States)
      python: 3.7
      env: TOTEST=docs/notebooks/06_example_3states.ipynb TOXENV=py37-test TRAVISCMD=""
    - name: Notebook 7 (Perfect Entanglers)
      python: 3.7
      env: TOTEST=docs/notebooks/07_example_PE.ipynb TOXENV=py37-test TRAVISCMD=""
    - name: Notebook 8 (Ensemble Optimization)
      python: 3.7
      env: TOTEST=docs/notebooks/08_example_ensemble.ipynb TRAVISCMD=travis_wait TOXENV=py37-test TRAVISCMD=travis_wait
    - name: Notebook 9 (NumPy)
      python: 3.7
      env: TOTEST=docs/notebooks/09_example_numpy.ipynb TOXENV=py37-test TRAVISCMD=""
  allow_failures:
    - name: Python 3.8-dev
before_install:
    - sudo apt-get -y install liblapack-dev libblas-dev gfortran
install:
  - pip install tox
  - pip install codecov
  - pip install --upgrade cython
  - pip freeze
  - printenv
script:
  - if [[ "${TOXENV}" == "py38dev-test" ]]; then travis_wait 40 tox -c tox-pyenv.ini -e py38dev-runcmd -- python --version; fi
  - $TRAVISCMD tox -c tox-pyenv.ini -e $TOXENV -- $TOTEST
after_success:
  - codecov
