codecov:
  require_ci_to_pass: yes

coverage:
  precision: 1
  round: down
  range: "75...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

notify:
  after_n_builds: 11
  threshold: 1%

comment:
  layout: "diff,files,footer"
  behavior: default
  require_changes: no
  after_n_builds: 11
