name: py36
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - qutip
  - pip:
    - better-apidoc>=0.2.0
    - sphinx-rtd-theme<0.3
    - sphinx_autodoc_typehints
    - sphinxcontrib-bibtex
    - nbsphinx<0.4
    - gitpython
